---
- import_role:
    name: server
  vars:
    users:
      nexus:
        group: nexus

    user_groups:
      nexus:

    packages:
      - openjdk-8-jdk-headless

- name: Create required directories
  file:
    path: "{{ nexus_root_dir }}"
    state: directory
    owner: nexus
    group: nexus

- name: Disable Nexus service
  systemd:
    name: nexus
    state: stopped
  ignore_errors: true
    
- name: Fetch nexus package
  get_url:
    url: "http://download.sonatype.com/nexus/3/{{ nexus_package }}"
    dest: "{{ nexus_root_dir }}"
    owner: nexus
    group: nexus

- name: Unarchive nexus package
  unarchive:
    src: "{{ nexus_package_file }}"
    dest: "{{ nexus_root_dir }}"
    owner: nexus
    group: nexus
    remote_src: true

- name: Fix permissions
  file:
    path: "{{ nexus_root_dir }}"
    state: directory
    owner: nexus
    group: nexus
    recurse: true
  
- name: Create Nexus systemd file
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service

- name: Enable Nexus service
  systemd:
    name: nexus
    state: started
    enabled: true
    daemon_reload: true
